import { useEffect, useRef } from 'react';
import NextPage from '../components/NextPage';

const sections = [
    { eyebrow: '01 / Beginning', title: 'Curiosity became a craft.', text: 'I’m Mukelani N. Sindana, a graduate of iHub Africa in Gauteng, South Africa. Before dev work started, I picked up skills working in and around a bakery, and that background still shapes how I think about discipline, consistency, and building something useful. I came into development wanting to turn ideas into visible, functional experiences. The real turning point came after finishing my Netflix clone project: it showed me I wasn’t bad at this, I was just lost in my process. That was the moment “I might fail” started turning into “this is a problem I can solve.”', image: '/images/images.jpg', alt: 'A visual from Mukelani\'s project work' },
    { eyebrow: '02 / Method', title: 'I learn by making things real.', text: 'In week 1, I didn’t just lack confidence — I genuinely thought there was a wall somewhere ahead of me I wouldn’t get past. That belief turned out to be flat-out wrong. Now hard things like React, a broken deployment, or a stubborn bug are just problems to solve, not proof that I’ve hit a ceiling. I learn the tool a project actually needs when it needs it, which has meant working with browser state, APIs, React, Firebase Authentication, and Firestore instead of waiting until everything feels familiar. My AI journey has been similar: I used to want finished solutions because they were faster, but I had to learn that working code is not the same as understanding code. I now treat AI more like a debugging partner or second opinion, not something that finishes the work for me.', image: '/images/Screenshot 2026-06-15 110911.png', alt: 'Screenshot from an interactive project' },
    { eyebrow: '03 / Direction', title: 'Useful is a design decision.', text: 'I’m building toward my own bakery and eventually a web-development team for my bakery or used as an agency for other companies — not just landing a job. I like doing my own thing, and I try to be consistent in what I do while being compassionate toward people in my own way. I’m usually the first at the lunch area as soon as lunch starts, and I’ve learned to value quiet focus, real effort, and steady habits. Outside of code, I’m into baking, bass and acoustic guitar, gaming, skating, and reading. What matters to me is making digital experiences that support people, communicate clearly, and feel considered. I debug from using MDN documents as reference, listen to feedback, and use each project to sharpen the next one.', image: '/images/Screenshot 2026-07-06 093822.png', alt: 'Screenshot from a collaborative prototype project' }
];

export default function AboutPage() {
    const sectionRefs = useRef([]);
    useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.target.classList.toggle('is-visible', entry.isIntersecting)), { threshold: 0.18 }); sectionRefs.current.forEach((section) => section && observer.observe(section)); return () => observer.disconnect(); }, []);
    return <><section className="page-intro section-purple"><p className="eyebrow">About me</p><h1>A developer with a practical imagination.</h1><p>I’m interested in the space where a clear idea becomes something people can actually use.</p></section><section className="story-sections">{sections.map((section, index) => <article className={`story-section${index % 2 ? ' image-first' : ''}`} key={section.eyebrow} ref={(element) => { sectionRefs.current[index] = element; }}><div className="story-copy"><p className="eyebrow">{section.eyebrow}</p><h2>{section.title}</h2><p>{section.text}</p></div><figure><img src={section.image} alt={section.alt} loading="lazy" /></figure></article>)}</section><NextPage to="/skills" label="Skills" description="Next, see the skills and tools I use to turn ideas into working interfaces." /></>;
}
