import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

const emptyForm = { title: '', description: '', tags: '', category: '', live_url: '', source_url: '', featured: false, remove_image: false };
export default function AdminPage() {
    const navigate = useNavigate(); const [projects, setProjects] = useState([]); const [form, setForm] = useState(emptyForm); const [image, setImage] = useState(null); const [preview, setPreview] = useState(''); const [status, setStatus] = useState('');
    async function load() { const response = await fetch('/api/projects'); if (response.status === 401) { navigate('/login'); return; } setProjects(await response.json()); }
    useEffect(() => { load(); }, []);
    function update(event) { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value })); }
    function chooseImage(event) { const file = event.target.files[0] || null; setImage(file); if (file) setPreview(URL.createObjectURL(file)); }
    function edit(project) { setForm({ title: project.title, description: project.description, tags: project.tags.join(', '), category: project.category || '', live_url: project.live_url, source_url: project.source_url, featured: project.featured, remove_image: false, id: project.id }); setImage(null); setPreview(project.image || ''); window.scrollTo({ top: 0, behavior: 'smooth' }); }
    function clear() { setForm(emptyForm); setImage(null); setPreview(''); }
    async function save(event) { event.preventDefault(); setStatus(''); const data = new FormData(); Object.entries(form).forEach(([key, value]) => key !== 'id' && data.append(key, String(value))); if (image) data.append('image', image); const response = await fetch(form.id ? `/api/projects/${form.id}` : '/api/projects', { method: form.id ? 'PUT' : 'POST', body: data }); const result = await response.json(); if (!response.ok) { setStatus(result.error || 'Unable to save project.'); return; } setStatus(form.id ? 'Project updated.' : 'Project added.'); clear(); load(); }
    async function remove(id) { if (!window.confirm('Delete this project from the portfolio?')) return; const response = await fetch(`/api/projects/${id}`, { method: 'DELETE' }); if (response.ok) { setStatus('Project deleted.'); load(); } }
    async function logout() { await fetch('/api/auth/logout', { method: 'POST' }); navigate('/login'); }
    return <main className="admin-content"><div className="admin-heading"><div><p className="eyebrow">Owner only</p><h1>Project dashboard</h1></div><p className="form-status" role="status">{status}</p></div><form className="project-form" onSubmit={save}><input type="hidden" name="id" value={form.id || ''} /><label htmlFor="title">Title</label><input id="title" name="title" value={form.title} onChange={update} required /><label htmlFor="description">Description</label><textarea id="description" name="description" rows="3" value={form.description} onChange={update} required /><label htmlFor="image">Project image</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={chooseImage} />{preview ? <div className="image-preview"><img src={preview} alt="Project preview" /></div> : <div className="image-preview">No image selected</div>}<label htmlFor="tags">Tags, separated by commas</label><input id="tags" name="tags" value={form.tags} onChange={update} placeholder="HTML, CSS, JavaScript" required /><label htmlFor="category">Category (optional)</label><input id="category" name="category" value={form.category} onChange={update} placeholder="Web app, UI clone, Full stack" /><label htmlFor="live_url">Live URL</label><input id="live_url" name="live_url" type="url" value={form.live_url} onChange={update} /><label htmlFor="source_url">Source URL</label><input id="source_url" name="source_url" type="url" value={form.source_url} onChange={update} /><label className="checkbox-label"><input name="featured" type="checkbox" checked={form.featured} onChange={update} /> Featured project</label><label className="checkbox-label"><input name="remove_image" type="checkbox" checked={form.remove_image} onChange={update} /> Remove current image</label><div className="project-form-actions"><button className="btn" type="submit">{form.id ? 'Update project' : 'Add project'}</button><button className="btn btn-outline" type="button" onClick={clear}>Clear</button><button className="btn btn-outline" type="button" onClick={logout}>Log out</button></div></form><section><h2>Published projects</h2><div className="admin-project-list">{projects.map((project) => <article className="admin-project-row" key={project.id}><div>{project.image && <img className="admin-project-thumb" src={project.image} alt="" />}<h3>{project.title}</h3><p>{project.description}</p><small>{project.category ? `${project.category} · ` : ''}{project.tags.join(' · ')}</small></div><div className="admin-row-actions"><button className="btn btn-small" type="button" onClick={() => edit(project)}>Edit</button><button className="btn btn-outline btn-small" type="button" onClick={() => remove(project.id)}>Delete</button></div></article>)}</div></section></main>;
}